### ISSUE TITLE
Streams Not Working

### ISSUE THREAD

**Issue by Rob2k9** [thehig/arconai-stream#2]
Hi i love the shows on offer from this website but suffered from the same problems as your self when i stumbled upon this i was amazed to see someone else had the same issues and had taken the time to find a way around it 

i checked out your : herokuapp test page and it loaded the m3u and let me save it but the issue i had was the streams wont play on my mobile via vlc player or mx player or even on my pc via vlc player

**Comment by thehig** [comment]
Can you give me some more information please? What mobile do you have? Is your version of VLC up to date?

**Comment by Rob2k9** [comment]
Hi i use sony experia xa1 for mobile testing and vlc is up to date on the android device 

using windows vlc is up to date for the latest version from official downloads

**Comment by thehig** [comment]
So, before I answer I just want to clarify that if you're able to resolve the m3u8 stream URL then _my_ code is working fine. 

In relation to your mobile handset, I've found that Chrome is perfectly capable of opening the stream natively, as is the Brave browser. I have also used BS Player on android with some success.

On PC I use a Chrome plugin (linked in the main readme). VLC is my main media player, but I've found it doesn't work properly for these streams

**Comment by Rob2k9** [comment]
i have done some digging and i see that when the m3u is loaded it opens fine but when the .ts files are tried to play it shows 403 forbidden as i think the site its self is now using some kind of blocking to make sure streams only play from there own site maybe a same origen policy

**Comment by thehig** [comment]
What are you trying to do? If you just open the m3u file with a compatible player it'll work

**Comment by Rob2k9** [comment]
i am trying to play the files and i can assure you that is dosent play i have tried the latest version of vlc for mobile and for windows 10 and none play i have tried here in the uk and using a vpn for diffrent countries 

i can however view the channels fine on the website its self

**Comment by thehig** [comment]
As I've said before:
- If you're able to resolve the m3u8 stream URL then my code is working fine
- VLC is my main media player, but I've found it doesn't work properly for these streams. Try another player

Since nothing here is actually a bug report about anything I have control over I'm gonna close this
